version: '3'

services:

  db:
    container_name: MYSQL
    image: mysql
    volumes:
      - ./mysql:/data/db
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
     

    